### ISSUE TITLE
in youtube_stream_image folder docker-compose up -d  failed with error

### ISSUE THREAD

**Issue by xsa-dev** [gaborvecsei/RaspberryPi-Youtube-Live-Stream#11]
> [4/4] RUN pip3 install -r requirements.txt:
#7 0.941 Downloading/unpacking flask==0.12.2 (from -r requirements.txt (line 1))
#7 2.043 Downloading/unpacking Werkzeug>=0.7 (from flask==0.12.2->-r requirements.txt (line 1))
#7 2.532 Downloading/unpacking click>=2.0 (from flask==0.12.2->-r requirements.txt (line 1))
#7 2.882 Cleaning up...
#7 2.897 Exception:
#7 2.897 Traceback (most recent call last):
#7 2.897   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2595, in _dep_map
#7 2.897     return self.__dep_map
#7 2.897   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2457, in __getattr__
#7 2.897     raise AttributeError(attr)
#7 2.897 AttributeError: _DistInfoDistribution__dep_map
#7 2.897 
#7 2.897 During handling of the above exception, another exception occurred:
#7 2.897 
#7 2.897 Traceback (most recent call last):
#7 2.897   File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
#7 2.897     status = self.run(options, args)
#7 2.897   File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
#7 2.897     requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
#7 2.897   File "/usr/lib/python3/dist-packages/pip/req.py", line 1266, in prepare_files
#7 2.897     req_to_install.extras):
#7 2.897   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2401, in requires
#7 2.897     dm = self._dep_map
#7 2.897   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2597, in _dep_map
#7 2.897     self.__dep_map = self._compute_dependencies()
#7 2.897   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2630, in _compute_dependencies
#7 2.897     common = frozenset(reqs_for_extra(None))
#7 2.897   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2627, in reqs_for_extra
#7 2.897     if req.marker_fn(override={'extra':extra}):
#7 2.897   File "/usr/lib/python3/dist-packages/_markerlib/markers.py", line 113, in marker_fn
#7 2.897     return eval(compiled_marker, environment)
#7 2.897   File "<environment marker>", line 1, in <module>
#7 2.897 NameError: name 'platform_system' is not defined
#7 2.897 
#7 2.898 Storing debug log for failure in /root/.pip/pip.log
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c pip3 install -r requirements.txt]: exit code: 2

**Comment by mpilosov** [comment]
i got it working, here's a patch (note my video device differs):

```
diff --git a/base_docker_image/Dockerfile b/base_docker_image/Dockerfile
index 8742b56..87a8f2e 100644
--- a/base_docker_image/Dockerfile
+++ b/base_docker_image/Dockerfile
@@ -1,4 +1,4 @@
-FROM debian:jessie
+FROM debian:bullseye
 
 RUN apt-get -q update && \
         apt-get install -y \
diff --git a/youtube_stream_image/Dockerfile b/youtube_stream_image/Dockerfile
index 9af1d30..a472cdf 100644
--- a/youtube_stream_image/Dockerfile
+++ b/youtube_stream_image/Dockerfile
@@ -2,7 +2,8 @@ FROM base_image:0.1.0
 
 RUN apt-get -q update && \
         apt-get install -qy \
-                libav-tools
+                ffmpeg
 
+RUN pip3 install --upgrade setuptools
 COPY requirements.txt requirements.txt
 RUN pip3 install -r requirements.txt
diff --git a/youtube_stream_image/code/simple_youtube_stream.sh b/youtube_stream_image/code/simple_youtube_stream.sh
index 6a9a381..374b195 100644
--- a/youtube_stream_image/code/simple_youtube_stream.sh
+++ b/youtube_stream_image/code/simple_youtube_stream.sh
@@ -5,7 +5,7 @@
 
 VIDEO_DEVICE=${1:-video0}
 
-avconv -loglevel info -ar 44100 -ac 2 -f s16le -i /dev/zero \
-        -f video4linux2 -s 640x480 -r 10 -i /dev/${VIDEO_DEVICE} \
-        -vf "drawtext=fontfile=/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf:text='%{localtime\:%T}': fontcolor=white@0.8: x=0: y=0" \
+ffmpeg -loglevel info -ar 44100 -ac 2 -f s16le -i /dev/zero \
+        -f video4linux2 -s 640x640 -r 10 -i /dev/${VIDEO_DEVICE} \
+        -vf "drawtext=fontfile=/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf:text='%{localtime\:%T}': fontcolor=white@0.6: fontsize=12: x=0: y=0" \
         -qscale:v 2 -f flv rtmp://a.rtmp.youtube.com/live2/${YOUTUBE_LIVE_KEY}
diff --git a/youtube_stream_image/code/youtube_stream.py b/youtube_stream_image/code/youtube_stream.py
index c26e4a1..4a2fd5e 100644
--- a/youtube_stream_image/code/youtube_stream.py
+++ b/youtube_stream_image/code/youtube_stream.py
@@ -4,8 +4,8 @@ import subprocess
 YOUTUBE_LIVE_KEY = os.environ['YOUTUBE_LIVE_KEY']
 
 # avconv has the same functionality as ffmpeg
-STREAM_COMMAND = ["avconv", "-loglevel", "quiet", "-ar", "44100", "-ac", "2", "-f", "s16le", "-i", "/dev/zero", "-f", "video4linux2", "-s",
-                  "640x360", "-r", "10", "-i", "/dev/video0", "-f", "flv",
+STREAM_COMMAND = ["ffmpeg", "-loglevel", "quiet", "-ar", "44100", "-ac", "2", "-f", "s16le", "-i", "/dev/zero", "-f", "video4linux2", "-s",
+                  "640x640", "-r", "10", "-i", "/dev/video0", "-f", "h264",
                   "rtmp://a.rtmp.youtube.com/live2/{0}".format(YOUTUBE_LIVE_KEY)]
 
 
diff --git a/youtube_stream_image/docker-compose.yml b/youtube_stream_image/docker-compose.yml
index 4c4e4ff..062a76a 100644
--- a/youtube_stream_image/docker-compose.yml
+++ b/youtube_stream_image/docker-compose.yml
@@ -10,10 +10,10 @@ services:
     volumes:
       - ./code:/code
     environment:
-      - YOUTUBE_LIVE_KEY=<YOUR_YOUTUBE_LIVE_STREAM_KEY>
+      - YOUTUBE_LIVE_KEY=<YOUR_YOUTUBE_LIVE_STREAM_KEY>
     devices:
-      - /dev/video0:/dev/video0
+      - /dev/video2:/dev/video0
     restart: unless-stopped
     entrypoint:
       - /bin/bash
-      - /code/simple_youtube_stream.sh
\ No newline at end of file
+      - /code/simple_youtube_stream.sh
diff --git a/youtube_stream_image/requirements.txt b/youtube_stream_image/requirements.txt
index 69ca547..7e10602 100644
--- a/youtube_stream_image/requirements.txt
+++ b/youtube_stream_image/requirements.txt
@@ -1 +1 @@
-flask==0.12.2
\ No newline at end of file
+flask
```

**Comment by xsa-dev** [comment]
Thank you!
