### ISSUE TITLE
Issue building base image

### ISSUE THREAD

**Issue by Bren00x** [gaborvecsei/RaspberryPi-Youtube-Live-Stream#6]
When I run: 
`pi@raspberrypi:~/YouTube-Live-Stream-Docker $ sudo ./base_docker_image/build_base.sh
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/pi/YouTube-Live-Stream-Docker/Dockerfile: no such file or directory`

also cannot find variable `STOP_WHEN_PRESENT_MAC_DICT` in `master_app_image/code/start_app.py`

I'm currently testing this on my raspberry pi running Raspbian GNU/Linux 9 (stretch). ffmpeg built with other tests. Using Logitech Webcam C930e.

**Comment by gaborvecsei** [comment]
```
$ cd base_docker_image
$ sudo ./build_base.sh
```

This should do the trick 👍

**Comment by gaborvecsei** [comment]
Thanks for pointing out `STOP_WHEN_PRESENT_MAC_DICT` I updated the README. In the last version I changed that dict to a separate csv file, this is why you did not found it.
