### ISSUE TITLE
Could not load fontface

### ISSUE THREAD

**Issue by notiles** [gaborvecsei/RaspberryPi-Youtube-Live-Stream#8]
Hello,

I get this error in the console logs : 

Could not load fontface from files 'usr/share/fonts/dejavu/DejaVuSans-Bold.ttf' : cannot open resource

The DejaVuSans-Bold.ttf file is present in the folder usr/share/fonts/dejavu 

Any idea ?

**Comment by notiles** [comment]
I remove the line -vf "drawtext= ... in simple_youtube_stream.sh and now it work fine!

**Comment by sebastianwachter** [comment]
Had the same error but after removing that line @notiles mentioned fixed it for me as well.
